### ISSUE TITLE
Infinite loop while running ./plist-websocket-proxy.rb

### ISSUE THREAD

**Issue by RSNara** [SoftwareMansion/react-native-android-jsc-debugging#1]
The console logs:

```BASH
Connection broken
./plist-websocket-proxy.rb:93:in `loop_body'
./plist-websocket-proxy.rb:86:in `block in interal_loop'
./plist-websocket-proxy.rb:86:in `loop'
./plist-websocket-proxy.rb:86:in `interal_loop'
./plist-websocket-proxy.rb:81:in `block in main_loop'
./plist-websocket-proxy.rb:78:in `loop'
./plist-websocket-proxy.rb:78:in `main_loop'
./plist-websocket-proxy.rb:127:in `block in <class:Proxy>'
Connection broken
./plist-websocket-proxy.rb:93:in `loop_body'
./plist-websocket-proxy.rb:86:in `block in interal_loop'
./plist-websocket-proxy.rb:86:in `loop'
./plist-websocket-proxy.rb:86:in `interal_loop'
./plist-websocket-proxy.rb:81:in `block in main_loop'
./plist-websocket-proxy.rb:78:in `loop'
./plist-websocket-proxy.rb:78:in `main_loop'
./plist-websocket-proxy.rb:127:in `block in <class:Proxy>'
```

Is there any debug information I could provide to help get to the bottom of this?

**Edit:** It seems like this is happening because the socket didn't receive any data.

**Comment by RSNara** [comment]
Pretty sure this happened because I used the precompiled jsc straight from npm. As such, there was no data being sent from the simulator to this script, which is probably why we run into this infinite loop.
